# Demonology Configuration File
# Edit this file to customize your mystical CLI experience

api:
  base_url: "http://127.0.0.1:8080/v1"
  model: "Qwen-3-14B"
  max_tokens: 1024
  temperature: 0.7
  top_p: 0.95
  timeout: 180.0  # Increased to 3 minutes for more stability
  max_retries: 5  # More retry attempts
  retry_delay: 3.0  # Longer delay between retries
  context_length: 26768  # Match your server's context length
  context_buffer: 2048   # Reserved tokens for response generation
  auto_trim_threshold: 0.85  # Auto-trim when 85% full
  smart_trimming: true   # Enable intelligent message preservation

ui:
  theme: "infernal"  # Options: amethyst, infernal, stygian
  permissive_mode: true
  auto_save_conversations: true
  max_history_length: 1000

tools:
  enabled: true
  allowed_tools:
    - "file_operations"     # File system operations
    - "code_execution"      # Run code snippets (Python, JS, Bash)
    - "web_search"          # Search the web for information
    - "reddit_search"       # Search Reddit discussions
    - "project_planning"    # Generate and execute project plans
    - "image_generation"    # Generate AI images for textures, icons, assets
    - "disassembler"        # Disassemble binary files using various disassemblers
    - "hex_editor"          # Hex dump, search, and edit binary files
    - "pattern_search"      # Search for patterns, strings, and signatures in binary files
    - "debugger"            # Debug binaries using GDB with scripting support
    - "ghidra_analysis"     # Perform headless binary analysis using Ghidra
    - "model3d_generator"   # Generate 3d models
  working_directory: null  # null means use current directory

# Optional: Reddit API configuration for enhanced search
# Set these environment variables for authenticated Reddit access:
# REDDIT_CLIENT_ID=your_client_id
# REDDIT_CLIENT_SECRET=your_client_secret  
# REDDIT_USER_AGENT=your_app_name
