api:
  base_url: http://127.0.0.1:8080/v1
  model: Qwen-3-14B
  max_tokens: 1024
  temperature: 0.7
  top_p: 0.95
  timeout: 180.0
  max_retries: 5
  retry_delay: 3.0
  context_length: 26768
  context_buffer: 2048

security:
  # Pin this to your actual workspace path so the guard knows where “inside” is.
  workspace_root: /home/k/Desktop/rewow

  allow_external_commands:
    - audiveris
    - r2
    - radare2
    - objdump
    - gdb
    - analyzeHeadless
    - mpq       # mpq-tools (if installed as `mpq`)
    - mpqcli    # StormLib-based CLI (if installed as `mpqcli`)

  allow_tools:
    - model3d_generator
    - sheet_music_omr
    - heightmap_generator
    - wow_world_converter
    - wow_model_converter
    - wow_scene_bundler
    - mpq_extractor
    - wow_archive_orchestrator
    - wow_auto_scene
    # Optional helpers if you plan to list dirs/read files in the UI:
    - file_operations
    - codebase_analysis

  # (Optional) extra places you want readable; keeping it minimal is safer.
  path_allowlist:
    - /home/k/Desktop/rebellion
    - /home/k/Desktop/Demonology
    - /home/k/Desktop/ExtractedWoW
    - /home/k/Desktop/rewow     # add your actual workspace explicitly

web:
  providers: [duckduckgo, wikipedia, hackernews, stackoverflow, openwebsearch]

tools:
  defaults:
    output_dir: outputs

  wow_world_converter:
    default_output_dir: wow_exports

  model3d_generator:
    default_output_dir: models

  sheet_music_omr:
    audiveris_bin: ${AUDIVERIS_BIN}
    tesseract_langs: [eng]

